# Generated by Django 4.1.7 on 2023-04-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=64)),
                ('preço', models.IntegerField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
