# Generated by Django 4.1.7 on 2023-04-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='preço',
            new_name='preco',
        ),
    ]
