# Generated by Django 4.2 on 2023-04-14 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_rename_preço_evento_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listas', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='preco',
            field=models.IntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='quantidade',
            field=models.IntegerField(verbose_name=0),
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomes', to='listas.slc')),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='listas.slc'),
        ),
    ]
