# Generated by Django 4.2 on 2023-04-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0003_slc_alter_evento_preco_alter_evento_quantidade_lista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='produto',
            field=models.CharField(max_length=64),
        ),
    ]
