# Generated by Django 4.2 on 2023-04-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0004_alter_evento_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='nome',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='slc',
            name='listas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomes', to='listas.lista'),
        ),
    ]
