# Generated by Django 4.2 on 2023-04-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0007_product_delete_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='SLC',
        ),
    ]
